export type CountryOption = {
  code: string;
  name: string;
  currency: string;
  defaultTimezone: string;
};

export const COUNTRY_OPTIONS: CountryOption[] = [
  { code: "IT", name: "Italia", currency: "EUR", defaultTimezone: "Europe/Rome" },
  { code: "AL", name: "Albania", currency: "ALL", defaultTimezone: "Europe/Tirane" },
  { code: "AD", name: "Andorra", currency: "EUR", defaultTimezone: "Europe/Andorra" },
  { code: "AM", name: "Armenia", currency: "AMD", defaultTimezone: "Asia/Yerevan" },
  { code: "AT", name: "Austria", currency: "EUR", defaultTimezone: "Europe/Vienna" },
  { code: "AZ", name: "Azerbaigian", currency: "AZN", defaultTimezone: "Asia/Baku" },
  { code: "BY", name: "Bielorussia", currency: "BYN", defaultTimezone: "Europe/Minsk" },
  { code: "BE", name: "Belgio", currency: "EUR", defaultTimezone: "Europe/Brussels" },
  { code: "BA", name: "Bosnia ed Erzegovina", currency: "BAM", defaultTimezone: "Europe/Sarajevo" },
  { code: "BG", name: "Bulgaria", currency: "BGN", defaultTimezone: "Europe/Sofia" },
  { code: "HR", name: "Croazia", currency: "EUR", defaultTimezone: "Europe/Zagreb" },
  { code: "CY", name: "Cipro", currency: "EUR", defaultTimezone: "Asia/Nicosia" },
  { code: "CZ", name: "Repubblica Ceca", currency: "CZK", defaultTimezone: "Europe/Prague" },
  { code: "DK", name: "Danimarca", currency: "DKK", defaultTimezone: "Europe/Copenhagen" },
  { code: "EE", name: "Estonia", currency: "EUR", defaultTimezone: "Europe/Tallinn" },
  { code: "FI", name: "Finlandia", currency: "EUR", defaultTimezone: "Europe/Helsinki" },
  { code: "CH", name: "Svizzera", currency: "CHF", defaultTimezone: "Europe/Zurich" },
  { code: "FR", name: "Francia", currency: "EUR", defaultTimezone: "Europe/Paris" },
  { code: "GE", name: "Georgia", currency: "GEL", defaultTimezone: "Asia/Tbilisi" },
  { code: "DE", name: "Germania", currency: "EUR", defaultTimezone: "Europe/Berlin" },
  { code: "GR", name: "Grecia", currency: "EUR", defaultTimezone: "Europe/Athens" },
  { code: "HU", name: "Ungheria", currency: "HUF", defaultTimezone: "Europe/Budapest" },
  { code: "IS", name: "Islanda", currency: "ISK", defaultTimezone: "Atlantic/Reykjavik" },
  { code: "IE", name: "Irlanda", currency: "EUR", defaultTimezone: "Europe/Dublin" },
  { code: "XK", name: "Kosovo", currency: "EUR", defaultTimezone: "Europe/Belgrade" },
  { code: "LV", name: "Lettonia", currency: "EUR", defaultTimezone: "Europe/Riga" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", defaultTimezone: "Europe/Vaduz" },
  { code: "LT", name: "Lituania", currency: "EUR", defaultTimezone: "Europe/Vilnius" },
  { code: "LU", name: "Lussemburgo", currency: "EUR", defaultTimezone: "Europe/Luxembourg" },
  { code: "MT", name: "Malta", currency: "EUR", defaultTimezone: "Europe/Malta" },
  { code: "MD", name: "Moldavia", currency: "MDL", defaultTimezone: "Europe/Chisinau" },
  { code: "MC", name: "Monaco", currency: "EUR", defaultTimezone: "Europe/Monaco" },
  { code: "ME", name: "Montenegro", currency: "EUR", defaultTimezone: "Europe/Podgorica" },
  { code: "NL", name: "Paesi Bassi", currency: "EUR", defaultTimezone: "Europe/Amsterdam" },
  { code: "MK", name: "Macedonia del Nord", currency: "MKD", defaultTimezone: "Europe/Skopje" },
  { code: "NO", name: "Norvegia", currency: "NOK", defaultTimezone: "Europe/Oslo" },
  { code: "PL", name: "Polonia", currency: "PLN", defaultTimezone: "Europe/Warsaw" },
  { code: "ES", name: "Spagna", currency: "EUR", defaultTimezone: "Europe/Madrid" },
  { code: "PT", name: "Portogallo", currency: "EUR", defaultTimezone: "Europe/Lisbon" },
  { code: "RO", name: "Romania", currency: "RON", defaultTimezone: "Europe/Bucharest" },
  { code: "SM", name: "San Marino", currency: "EUR", defaultTimezone: "Europe/San_Marino" },
  { code: "RS", name: "Serbia", currency: "RSD", defaultTimezone: "Europe/Belgrade" },
  { code: "SK", name: "Slovacchia", currency: "EUR", defaultTimezone: "Europe/Bratislava" },
  { code: "SI", name: "Slovenia", currency: "EUR", defaultTimezone: "Europe/Ljubljana" },
  { code: "SE", name: "Svezia", currency: "SEK", defaultTimezone: "Europe/Stockholm" },
  { code: "TR", name: "Turchia", currency: "TRY", defaultTimezone: "Europe/Istanbul" },
  { code: "UA", name: "Ucraina", currency: "UAH", defaultTimezone: "Europe/Kyiv" },
  { code: "VA", name: "Citta del Vaticano", currency: "EUR", defaultTimezone: "Europe/Vatican" },
  { code: "GB", name: "Regno Unito", currency: "GBP", defaultTimezone: "Europe/London" },
  { code: "IL", name: "Israele", currency: "ILS", defaultTimezone: "Asia/Jerusalem" },
  { code: "SA", name: "Arabia Saudita", currency: "SAR", defaultTimezone: "Asia/Riyadh" },
  { code: "QA", name: "Qatar", currency: "QAR", defaultTimezone: "Asia/Qatar" },
  { code: "JP", name: "Giappone", currency: "JPY", defaultTimezone: "Asia/Tokyo" },
  { code: "SG", name: "Singapore", currency: "SGD", defaultTimezone: "Asia/Singapore" },
  { code: "HK", name: "Hong Kong", currency: "HKD", defaultTimezone: "Asia/Hong_Kong" },
  { code: "US", name: "Stati Uniti", currency: "USD", defaultTimezone: "America/New_York" },
  { code: "CA", name: "Canada", currency: "CAD", defaultTimezone: "America/Toronto" },
  { code: "MX", name: "Messico", currency: "MXN", defaultTimezone: "America/Mexico_City" },
  { code: "BR", name: "Brasile", currency: "BRL", defaultTimezone: "America/Sao_Paulo" },
  { code: "AR", name: "Argentina", currency: "ARS", defaultTimezone: "America/Argentina/Buenos_Aires" },
  { code: "ZA", name: "Sudafrica", currency: "ZAR", defaultTimezone: "Africa/Johannesburg" },
  { code: "AU", name: "Australia", currency: "AUD", defaultTimezone: "Australia/Sydney" },
  { code: "NZ", name: "Nuova Zelanda", currency: "NZD", defaultTimezone: "Pacific/Auckland" },
  { code: "AE", name: "Emirati Arabi Uniti", currency: "AED", defaultTimezone: "Asia/Dubai" },
];

export function getCountryMeta(code?: string | null) {
  if (!code) return COUNTRY_OPTIONS[0];
  return COUNTRY_OPTIONS.find((c) => c.code === code.toUpperCase()) ?? COUNTRY_OPTIONS[0];
}
